version: '2'

services:
#  postgres:
#    image: 'postgres:10.3-alpine'
#    volumes:
#      - 'postgres:/var/lib/postgresql/data'
#    env_file:
#      - '.env'

  redis:
    image: 'redis:alpine'
    container_name: redis
#    command: redis-server --requirepass yourpassword
#~    command: redis-server
    volumes:
      - 'redis:/data'

  website: &base
    depends_on:
#      - 'postgres'
      - 'redis'
    build: .
    environment:
      REDIS_URL: redis://redis:6379
    ports:
      - '3000:3000'
#    volumes:
#      - '.:/app'

  sidekiq:
#    <<: *base
    depends_on:
#      - 'postgres'
      - 'redis'
    build: .
#    command: sidekiq -C config/sidekiq.yml.erb
    command: sidekiq -C config/sidekiq.yml
    environment:
      REDIS_URL: redis://redis:6379
#    volumes:
#      - '.:/app'
#    env_file:
#      - '.env'

#  cable:
#    depends_on:
#      - 'redis'
#    build: .
#    command: puma -p 28080 cable/config.ru
#    ports:
#      - '28080:28080'
#    volumes:
#      - '.:/app'
#    env_file:
#      - '.env'

volumes:
  redis:
  postgres:
