version: '2'

services:
  redis:
    image: 'redis:alpine'
    container_name: redis
    volumes:
      - 'redis:/data'

  website:
    depends_on:
      - 'redis'
    build: .
    environment:
      REDIS_URL: redis://redis:6379
    # dołożyć normalną bazę -> postgres
    # connection-stringi i credentiale w ramach zmiennych środowiskowych; na razie może być w docker-compose, docelowo w .env
#    ports:
#      - '3000:3000'

  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    depends_on:
      - 'website'
    ports:
      - '80:80'

  sidekiq:
    depends_on:
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml
    environment:
      REDIS_URL: redis://redis:6379

  crono:
    build: .
    command: bundle exec crono
    environment:
      REDIS_URL: redis://redis:6379

volumes:
  redis:
  postgres:
